// prettier-ignore
let number = [
  { color: 'green', type: 'zero', postion: 'zero', side: 'zero', row: 'zero' },
  {color: 'red',type: 'odd',postion: 'first',side: 'firstHalf',row: 'bottom'},
  {color: 'black',type: 'even',postion: 'first',side: 'firstHalf',row: 'middle'},
  {color: 'red',type: 'odd',postion: 'first',side: 'firstHalf',row: 'top'},
  {color: 'black',type: 'even',postion: 'first',side: 'firstHalf',row: 'bottom'},
  {color: 'red',type: 'odd',postion: 'first',side: 'firstHalf',row: 'middle'},
  {color: 'black',type: 'even',postion: 'first',side: 'firstHalf',row: 'top'},
  {color: 'red',type: 'odd',postion: 'first',side: 'firstHalf',row: 'bottom'},
  {color: 'black',type: 'even',postion: 'first',side: 'firstHalf',row: 'middle'},
  {color: 'red',type: 'odd',postion: 'first',side: 'firstHalf',row: 'top'},
  {color: 'black',type: 'even',postion: 'first',side: 'firstHalf',row: 'bottom'},
  {color: 'black',type: 'odd',postion: 'first',side: 'firstHalf',row: 'middle'},
  {color: 'red',type: 'even',postion: 'first',side: 'firstHalf',row: 'top'},

  {color: 'black',type: 'odd',postion: 'second',side: 'firstHalf',row: 'bottom'},
  {color: 'red',type: 'even',postion: 'second',side: 'firstHalf',row: 'middle'},
  {color: 'black',type: 'odd',postion: 'second',side: 'firstHalf',row: 'top'},
  {color: 'red',type: 'even',postion: 'second',side: 'firstHalf',row: 'bottom'},
  {color: 'black',type: 'odd',postion: 'second',side: 'firstHalf',row: 'middle'},
  {color: 'red',type: 'even',postion: 'second',side: 'firstHalf',row: 'top'},
  {color: 'red',type: 'odd',postion: 'second',side: 'secondHalf',row: 'bottom'},
  {color: 'black',type: 'even',postion: 'second',side: 'secondHalf',row: 'middle'},
  {color: 'red',type: 'odd',postion: 'second',side: 'secondHalf',row: 'top'},
  {color: 'black',type: 'even',postion: 'second',side: 'secondHalf',row: 'bottom'},
  {color: 'red',type: 'odd',postion: 'second',side: 'secondHalf',row: 'middle'},
  {color: 'black',type: 'even',postion: 'second',side: 'secondHalf',row: 'top'},

  {color: 'red',type: 'odd',postion: 'third',side: 'secondHalf',row: 'bottom'},
  {color: 'black',type: 'even',postion: 'third',side: 'secondHalf',row: 'middle'},
  {color: 'red',type: 'odd',postion: 'third',side: 'secondHalf',row: 'top'},
  {color: 'black',type: 'even',postion: 'third',side: 'secondHalf',row: 'bottom'},
  {color: 'black',type: 'odd',postion: 'third',side: 'secondHalf',row: 'middle'},
  {color: 'red',type: 'even',postion: 'third',side: 'secondHalf',row: 'top'},
  {color: 'black',type: 'odd',postion: 'third',side: 'secondHalf',row: 'bottom'},
  {color: 'red',type: 'even',postion: 'third',side: 'secondHalf',row: 'middle'},
  {color: 'black',type: 'odd',postion: 'third',side: 'secondHalf',row: 'top'},
  {color: 'red',type: 'even',postion: 'third',side: 'secondHalf',row: 'bottom'},
  {color: 'black',type: 'odd',postion: 'third',side: 'secondHalf',row: 'middle'},
  {color: 'red',type: 'even',postion: 'third',side: 'secondHalf',row: 'top'},
];

module.exports = number;
